config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Animal.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Animal extends Entity
{
    protected $_accessible = [
        'name' => true,
        'email' => true,
        'date_of_birth' => true,
        'address' => true,
        'image' => true,
        'user_id' => true,
        'animal_category_id'=>true,
        'created' => true,
        'modified' => true,
        'user' => true
    ];
}

src/Model/Table/AnimalsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;


class AnimalsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('animals');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);

        $this->belongsTo('AnimalCategories', [
            'foreignKey' => 'animal_category_id',
        ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        // $validator
        //     ->scalar('name')
        //     ->maxLength('name', 50)
        //     ->requirePresence('name', 'create')
        //     ->notEmpty('name');

        // $validator
        //     ->email('email')
        //     ->requirePresence('email', 'create')
        //     ->notEmpty('email');

        // $validator
        //     ->date('date_of_birth')
        //     ->requirePresence('date_of_birth', 'create')
        //     ->notEmpty('date_of_birth');

        // $validator
        //     ->scalar('address')
        //     ->requirePresence('address', 'create')
        //     ->notEmpty('address');

        // $validator
        //     ->scalar('image')
        //     ->maxLength('image', 255)
        //     ->requirePresence('image', 'create')
        //     ->notEmpty('image');

        return $validator;
    }

    
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['animal_category_id'], 'AnimalCategories'));
        return $rules;
    }
}

src/Controller/AnimalsController.php
<?php
namespace App\Controller;
use Cake\ORM\TableRegistry;
use App\Controller\AppController;


class AnimalsController extends AppController
{


    public function index()
    {
        $this->paginate = [
            'contain' => ['Users','AnimalCategories']
        ];
        $animals = $this->paginate($this->Animals);

        $this->set(compact('animals'));
    }

    public function view($id = null)
    {
        $animal = $this->Animals->get($id, [
            'contain' => ['Users']
        ]);

        $this->set('animal', $animal);
    }


    public function add()
    {
        $addressTable   = TableRegistry::get('Address');
        $animal = $this->Animals->newEntity();
        if ($this->request->is('post')) {
            $animal = $this->Animals->patchEntity($animal, $this->request->getData());
            $animal->user_id = $this->Auth->user('id');
            // debug($this->request->data['image']['name']);
            // exit();

            if(!empty($this->request->data['image']['name'])){
                $image_name = date("Y-m-d-H-i-s").str_replace( " ", "-", $this->request->data['image']['name'] );
                $image_tmp         = $this->request->data['image']['tmp_name'];
                $destination       = WWW_ROOT.'img'.DS.'animals'.DS.$image_name;
                move_uploaded_file($image_tmp, $destination);
                $animal->image = 'animals/'.$image_name;
            }

            if ($this->Animals->save($animal)) {
                $address = $addressTable->newEntity();
                $address->animal_id = 1;
                $address->address   = $this->request->data('address');
                $addressTable->save($address);
                $this->Flash->success(__('The animal has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The animal could not be saved. Please, try again.'));
        }
        $users = $this->Animals->Users->find('list', ['limit' => 200]);
        $animalCategories = $this->Animals->AnimalCategories->find('list', ['limit' => 200]);
        $this->set(compact('animal', 'users','animalCategories'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Animal id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $animal = $this->Animals->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $animal = $this->Animals->patchEntity($animal, $this->request->getData());
            if ($this->Animals->save($animal)) {
                $this->Flash->success(__('The animal has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The animal could not be saved. Please, try again.'));
        }
        $users = $this->Animals->Users->find('list', ['limit' => 200]);
        $this->set(compact('animal', 'users'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Animal id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $animal = $this->Animals->get($id);
        if ($this->Animals->delete($animal)) {
            $this->Flash->success(__('The animal has been deleted.'));
        } else {
            $this->Flash->error(__('The animal could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Animals/add.ctp
<div class="animals form large-9 medium-8 columns content">
    <?= $this->Form->create($animal,['type'=>'file']) ?>
    <fieldset>
        <legend><?= __('Animal register') ?></legend>
        <?php
            echo $this->Form->control('name',['class'=>'form-control','placeholder'=>'Name']);

            echo $this->Form->control('animal_category_id',['class'=>'form-control','placeholder'=>'Name','empty'=>'--Select One --']);

            echo $this->Form->control('email',['class'=>'form-control','placeholder'=>'Email']);
            echo $this->Form->control('date_of_birth',['type'=>'text','class'=>'form-control','id'=>'birthDate','placeholder'=>'YY-MM-DD']);
            echo $this->Form->control('address',['class'=>'form-control','placeholder'=>'Address..']);
        ?>
        <br>
        <?php 
            echo $this->Form->control('image',['type'=>'file','label'=>'Image:']);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit'),['class'=>'btn btn-outline-primary my-2 my-sm-0','style'=>"float: right"]) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Animals/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Animal $animal
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $animal->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $animal->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Animals'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Users'), ['controller' => 'Users', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New User'), ['controller' => 'Users', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="animals form large-9 medium-8 columns content">
    <?= $this->Form->create($animal) ?>
    <fieldset>
        <legend><?= __('Edit Animal') ?></legend>
        <?php
            echo $this->Form->control('name');
            echo $this->Form->control('email');
            echo $this->Form->control('date_of_birth');
            echo $this->Form->control('address');
            echo $this->Form->control('image');
            echo $this->Form->control('user_id', ['options' => $users]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Animals/index.ctp
<div class="animals index large-9 medium-8 columns content">
    <h3><?= __('Animals') ?></h3>
    <table class="table">
        <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('name') ?></th>
                <th scope="col"><?= $this->Paginator->sort('category') ?></th>

                <th scope="col"><?= $this->Paginator->sort('email') ?></th>
                <th scope="col"><?= $this->Paginator->sort('date_of_birth') ?></th>
                <th scope="col"><?= $this->Paginator->sort('image') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($animals as $animal): ?>
            <tr>
                <td><?= $this->Number->format($animal->id) ?></td>
                <td><?= h($animal->name) ?></td>
                <td><?= h($animal->animal_category->name) ?></td>

                <td><?= h($animal->email) ?></td>
                <td><?= h($animal->date_of_birth) ?></td>
                <td><?= $this->Html->image($animal->image,['style'=>'width:50px']) ?></td>
                <td><?= h($animal->created) ?></td>
                <td><?= h($animal->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $animal->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $animal->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $animal->id], ['confirm' => __('Are you sure you want to delete # {0}?', $animal->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

src/Template/Animals/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Animal $animal
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Animal'), ['action' => 'edit', $animal->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Animal'), ['action' => 'delete', $animal->id], ['confirm' => __('Are you sure you want to delete # {0}?', $animal->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Animals'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Animal'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Users'), ['controller' => 'Users', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New User'), ['controller' => 'Users', 'action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="animals view large-9 medium-8 columns content">
    <h3><?= h($animal->name) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('Name') ?></th>
            <td><?= h($animal->name) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Email') ?></th>
            <td><?= h($animal->email) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Image') ?></th>
            <td><?= h($animal->image) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('User') ?></th>
            <td><?= $animal->has('user') ? $this->Html->link($animal->user->id, ['controller' => 'Users', 'action' => 'view', $animal->user->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($animal->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Date Of Birth') ?></th>
            <td><?= h($animal->date_of_birth) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($animal->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($animal->modified) ?></td>
        </tr>
    </table>
    <div class="row">
        <h4><?= __('Address') ?></h4>
        <?= $this->Text->autoParagraph(h($animal->address)); ?>
    </div>
</div>